/* This file is part of the ArcLight engine (GPL v2 or later), see LICENSE.html */

#ifndef VFS_MODES_H
#define VFS_MODES_H

#define ARCLIGHT_VFS_PWD  "p"
#define ARCLIGHT_VFS_RAW  "r"
#define ARCLIGHT_VFS_MOD  "M"
#define ARCLIGHT_VFS_MAP  "m"
#define ARCLIGHT_VFS_BASE "b"
#define ARCLIGHT_VFS_MENU "e"
#define ARCLIGHT_VFS_NONE " "
#define ARCLIGHT_VFS_MOD_BASE   ARCLIGHT_VFS_MOD  ARCLIGHT_VFS_BASE
#define ARCLIGHT_VFS_MAP_BASE   ARCLIGHT_VFS_MAP  ARCLIGHT_VFS_BASE
#define ARCLIGHT_VFS_MENU_BASE  ARCLIGHT_VFS_MENU ARCLIGHT_VFS_BASE
#define ARCLIGHT_VFS_ZIP        ARCLIGHT_VFS_MOD  ARCLIGHT_VFS_MAP  ARCLIGHT_VFS_MENU  ARCLIGHT_VFS_BASE
#define ARCLIGHT_VFS_RAW_FIRST  ARCLIGHT_VFS_RAW  ARCLIGHT_VFS_ZIP
#define ARCLIGHT_VFS_ZIP_FIRST  ARCLIGHT_VFS_ZIP  ARCLIGHT_VFS_RAW
#define ARCLIGHT_VFS_ALL        ARCLIGHT_VFS_RAW_FIRST
#define ARCLIGHT_VFS_PWD_ALL    ARCLIGHT_VFS_PWD ARCLIGHT_VFS_ALL

#endif // VFS_MODES_H
