option(ARCLIGHT_ENABLE_MODERN_STACK "Enable C++23 SDL3/Vulkan/D3D12/ImGui/GLM/EnTT integration targets" ON)
option(ARCLIGHT_REQUIRE_MODERN_STACK "Fail configure when modern stack packages are missing" OFF)
option(ARCLIGHT_BUILD_MODERN_SMOKE "Build a compile/link smoke test for the modern stack" ON)

function(arclight_check_modern_compiler)
	if(NOT ARCLIGHT_ENABLE_MODERN_STACK)
		return()
	endif()

	if(MSVC)
		if(MSVC_VERSION LESS 1936)
			message(WARNING "C++23 support works best with latest MSVC. Detected MSVC_VERSION=${MSVC_VERSION}.")
		endif()
	elseif(CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
		if(CMAKE_CXX_COMPILER_VERSION VERSION_LESS 14)
			message(WARNING "C++23 support works best with GCC 14+. Detected ${CMAKE_CXX_COMPILER_VERSION}.")
		endif()
	elseif(CMAKE_CXX_COMPILER_ID MATCHES "Clang")
		if(CMAKE_CXX_COMPILER_VERSION VERSION_LESS 18)
			message(WARNING "C++23 support works best with Clang 18+. Detected ${CMAKE_CXX_COMPILER_VERSION}.")
		endif()
	endif()
endfunction()

function(arclight_find_modern_package out_var package_name)
	find_package(${package_name} CONFIG QUIET)
	if(${package_name}_FOUND)
		set(${out_var} TRUE PARENT_SCOPE)
	else()
		find_package(${package_name} QUIET)
		set(${out_var} ${${package_name}_FOUND} PARENT_SCOPE)
	endif()
endfunction()

function(arclight_configure_modern_stack)
	if(NOT ARCLIGHT_ENABLE_MODERN_STACK)
		message(STATUS "ArcLight modern stack support disabled")
		return()
	endif()

	arclight_check_modern_compiler()

	add_library(arclight_modern_stack INTERFACE)
	if(ARCLIGHT_CXX_STANDARD GREATER_EQUAL 23)
		target_compile_features(arclight_modern_stack INTERFACE cxx_std_23)
	elseif(ARCLIGHT_CXX_STANDARD EQUAL 20)
		target_compile_features(arclight_modern_stack INTERFACE cxx_std_20)
	else()
		target_compile_features(arclight_modern_stack INTERFACE cxx_std_17)
	endif()
	target_compile_definitions(arclight_modern_stack INTERFACE ARCLIGHT_MODERN_STACK=1)

	arclight_find_modern_package(ARCLIGHT_HAS_SDL3 SDL3)
	arclight_find_modern_package(ARCLIGHT_HAS_GLM glm)
	arclight_find_modern_package(ARCLIGHT_HAS_ENTT EnTT)
	arclight_find_modern_package(ARCLIGHT_HAS_IMGUI imgui)
	find_package(Vulkan QUIET)
	set(ARCLIGHT_HAS_VULKAN ${Vulkan_FOUND})

	set(ARCLIGHT_HAS_D3D12 FALSE)
	if(WIN32)
		find_library(ARCLIGHT_D3D12_LIBRARY d3d12)
		find_library(ARCLIGHT_DXGI_LIBRARY dxgi)
		find_library(ARCLIGHT_DXGUID_LIBRARY dxguid)
		if(ARCLIGHT_D3D12_LIBRARY AND ARCLIGHT_DXGI_LIBRARY AND ARCLIGHT_DXGUID_LIBRARY)
			set(ARCLIGHT_HAS_D3D12 TRUE)
		endif()
	endif()

	if(ARCLIGHT_HAS_SDL3)
		if(TARGET SDL3::SDL3)
			target_link_libraries(arclight_modern_stack INTERFACE SDL3::SDL3)
		elseif(TARGET SDL3::SDL3-shared)
			target_link_libraries(arclight_modern_stack INTERFACE SDL3::SDL3-shared)
		endif()
		target_compile_definitions(arclight_modern_stack INTERFACE ARCLIGHT_HAS_SDL3=1)
	endif()

	if(ARCLIGHT_HAS_GLM)
		if(TARGET glm::glm)
			target_link_libraries(arclight_modern_stack INTERFACE glm::glm)
		endif()
		target_compile_definitions(arclight_modern_stack INTERFACE ARCLIGHT_HAS_GLM=1)
	endif()

	if(ARCLIGHT_HAS_ENTT)
		if(TARGET EnTT::EnTT)
			target_link_libraries(arclight_modern_stack INTERFACE EnTT::EnTT)
		endif()
		target_compile_definitions(arclight_modern_stack INTERFACE ARCLIGHT_HAS_ENTT=1)
	endif()

	if(ARCLIGHT_HAS_IMGUI)
		if(TARGET imgui::imgui)
			target_link_libraries(arclight_modern_stack INTERFACE imgui::imgui)
		endif()
		target_compile_definitions(arclight_modern_stack INTERFACE ARCLIGHT_HAS_IMGUI=1)
	endif()

	if(ARCLIGHT_HAS_VULKAN)
		target_link_libraries(arclight_modern_stack INTERFACE Vulkan::Vulkan)
		target_compile_definitions(arclight_modern_stack INTERFACE ARCLIGHT_HAS_VULKAN=1)
	endif()

	if(ARCLIGHT_HAS_D3D12)
		target_link_libraries(arclight_modern_stack INTERFACE
			${ARCLIGHT_D3D12_LIBRARY}
			${ARCLIGHT_DXGI_LIBRARY}
			${ARCLIGHT_DXGUID_LIBRARY}
		)
		target_compile_definitions(arclight_modern_stack INTERFACE ARCLIGHT_HAS_D3D12=1)
	endif()

	set(_missing "")
	foreach(_dep SDL3 Vulkan glm EnTT imgui)
		string(TOUPPER "${_dep}" _dep_upper)
		if(NOT ARCLIGHT_HAS_${_dep_upper})
			list(APPEND _missing ${_dep})
		endif()
	endforeach()
	if(WIN32 AND NOT ARCLIGHT_HAS_D3D12)
		list(APPEND _missing D3D12)
	endif()

	if(_missing)
		if(ARCLIGHT_REQUIRE_MODERN_STACK)
			message(FATAL_ERROR "Missing required modern stack packages: ${_missing}")
		endif()
		message(STATUS "ArcLight modern stack available with missing optional packages: ${_missing}")
	else()
		message(STATUS "ArcLight modern stack found: C++23, SDL3, Vulkan, D3D12/Windows, Dear ImGui, GLM, EnTT")
	endif()

	if(ARCLIGHT_BUILD_MODERN_SMOKE AND ARCLIGHT_HAS_SDL3 AND ARCLIGHT_HAS_GLM AND ARCLIGHT_HAS_ENTT)
		add_executable(arclight_modern_smoke EXCLUDE_FROM_ALL
			${CMAKE_SOURCE_DIR}/tools/modern_smoke/main.cpp
		)
		target_link_libraries(arclight_modern_smoke PRIVATE arclight_modern_stack)
		target_compile_definitions(arclight_modern_smoke PRIVATE SDL_MAIN_HANDLED)
	endif()
endfunction()
